name: MobLoot
version: '${version}'
api-version: '1.19'
main: me.penguin.mobloot.MobLoot
commands:
  mobloot:
    description: Reloads the MobLoot config file.
    usage: /mobloot reload
    aliases: [ml]