DropEgg:
   #or drop an egg from a spawning mob when killed by the player.
   Enable: true
   #Egg drop chance spawning mob (0.0-1.0)
   Chance: 0.1 
CurrencyDrop:
   MinAmount: 10
   MaxAmount: 100
   #This line sends a message to the player about receiving currency.
   Msg: "You received {amount} currency for killing a {entity}."
ConfigReloadMsg: "&aConfig reloaded"
NotPermMsg: "&cYou do not have permission."  
Entity:
  '1':
#Name entity after killing which the command is executed.
#You can find the list of entities here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
    EntityName: ENDER_DRAGON
    Command: example command
    