DropEgg:
   #or drop an egg from a spawning mob when killed by the player.
   Enable: true
   #Egg drop chance spawning mob (0.0-1.0)
   Chance: 0.1 
   #Rename monster_egg to anvil
   #false rename
   #true do not rename 
   Rename: false
   #Summon a mob from an egg
   #false summon
   #true do not summon
   SpawnFromEgg: false
   Blacklist:
   - ENDER_DRAGON
CurrencyDrop:
   MinAmount: 10
   MaxAmount: 100
   #This line sends a message to the player about receiving currency.
   Message: "You received {amount} currency for killing a {entity}."
   #Drop an item with money from a mob after a kill
   DropItem:
    Enable: false
    Material: GOLD_INGOT
    Message: "You received {amount} currency."
   Blacklist:
   - ENDER_DRAGON
ConfigReloadMsg: "&aPlugin reloaded"
NotPermMsg: "&cYou do not have permission."  
Entity:
  '1':
#Name entity after killing which the command is executed.
#You can find the list of entities here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
    EntityName: ENDER_DRAGON
    Command: example command
    