name: MobLoot
version: 1.2.1
author: penguin
main: me.penguin.mobloot.mobloot
description:
commands:
  mobloot:
    description: Reloads the MobLoot config file.
    usage: /mobloot reload
    aliases: [ml]